---
title: 01. 단순회귀모형
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(error = TRUE)
```

## 1.2 단순회귀모형

```{r}
market <- read.csv("./data/ch01/market-1.csv")
head(market)
```

## 1.3 회귀선의 추정

### 1.3.1 최소제곱법

```{r}
market_lm <- lm(Y ~ X, data = market)
summary(market_lm)
```

### 1.3.2 잔차

```{r}
names(market_lm)
market_lm$resid
```

- 잔차들의 합은 0이다.
  ```{r}
sum(market_lm$resid)
  ```

- 관찰값 $Y_i$의 합과 추정값 $\hat{Y_i}$의 합은 같다

  ```{r}
sum(market$Y)
sum(market_lm$fitted)
  ```

- 잔차들의 $X_i$에 대한 가중합은 0이다.

  ```{r}
sum(market$X * market_lm$resid)
  ```

- 잔차들의 $\hat{Y_i}$에 대한 가중합은 0이다.

  ```{r}
sum(market_lm$fitted * market_lm$resid)
  ```

```{r}
par(family = "AppleGothic")
plot(market$X, market$Y, xlab = "인테리어비", ylab = "총판매액", pch = 19)
title("인테리어비와 판매액의 산점도")
abline(market_lm)

xbar <- mean(market$X)
ybar <- mean(market$Y)
c(xbar, ybar)
points(xbar, ybar, pch = 17, cex = 2.0, col = "RED")
text(xbar + 1.3, ybar, "(8.85, 19.36)")

fx <- "Y-hat = 0.33 + 2.15 * X"
text(xbar + 1, ybar - 3, fx)
```

## 1.4 단순회귀 분산분석표

### 1.4.1 분산분석표에 의한 F-검정

```{r}
anova(market_lm)
```

### 1.4.4 상관계수와 결정계수

```{r}
cor_xy <- cor(market$X, market$Y)
round(cor_xy^2, 4)
```

## 1.5 단순회귀의 추정과 검정

### 1.5.2 추정값의 신뢰구간

```{r}
pred_frame <- data.frame(X = seq(3.5, 14.5, 0.2))
pc <- predict(market_lm, interval = "confidence", newdata = pred_frame)
pp <- predict(market_lm, interval = "prediction", newdata = pred_frame)
head(pc)
head(pp)

pred_x <- pred_frame$X
pred_x

plot(market$X, market$Y, ylim = range(market$Y, pp))
matlines(pred_x, pc, lty = c(1, 2, 2), col = "BLUE")
matlines(pred_x, pp, lty = c(1, 3, 3), col = "RED")

market_predict <- predict(market_lm, interval = "predict")
all_data <- cbind(market, market_predict)
head(all_data)

library(ggplot2)
ggplot(all_data, aes(x = X, y = Y)) +
  geom_point() +
  stat_smooth(method = lm) +
  geom_line(aes(y = lwr), col = "coral2", linetype = "dashed") +
  geom_line(aes(y = upr), col = "coral2", linetype = "dashed")
```

### 1.5.3 $\beta_1$의 검정

```{r}
summary(market_lm)
t0 <- 2.1497 / 0.1548
2 * (1 - pt(t0, length(market$X) - 2))
```

## 1.7 분석 사례

```{r}
# 1. 자료파일 만들기

# 2. 자료를 읽어 산점도 그리기
super <- read.csv("./data/ch01/supermarket.csv")
head(super, 3)
plot(super$price, super$time, pch = 19)

# 3. 회귀모형 적합하기
super_lm <- lm(time ~ price, data = super)
summary(super_lm)

# 4. 분산분석표 구하기
anova(super_lm)

# 5. 잔차 및 추정값 보기
names(super_lm)
cbind(super, super_lm$resid, super_lm$fitted)

# 6. 잔차그림 그리기
plot(super$price, super_lm$resid, pch = 19)
abline(h = 0, lty = 2)

# 7. 추정값의 신뢰대 그리기
super_predict <- predict(super_lm, interval = "predict")
super_data <- cbind(super, super_predict)
ggplot(super_data, aes(x = price, y = time)) +
  geom_point() +
  stat_smooth(method = lm) +
  geom_line(aes(y = lwr), col = "coral2", linetype = "dashed") +
  geom_line(aes(y = upr), col = "coral2", linetype = "dashed")
```
