---
title: 02. 중회귀모형
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(error = TRUE)

library(lm.beta)
library(purrr)
```

### 01.

```{r}
data <- read.csv("./data/ch02/ex2-1.csv")
head(data)

# 1)
model <- lm(Y ~ X1 + X2, data = data)
summary(model)

# 2)
x <- cbind(1, data[, -3]) |> as.matrix()
xt <- t(x)
xtxi <- solve(xt %*% x)
hat <- x %*% xtxi %*% xt

y <- as.matrix(data$Y)
yt <- t(y)
n <- length(y)
i <- diag(n)
mse <- yt %*% (i - hat) %*% y / (n - 3)
mse <- mse[1, 1]

t(x) %*% x * mse

# 3)
newdata <- data.frame(X1 = 200, X2 = 59)
predict(model, int = "c", se.fit = TRUE, newdata = newdata)

# 4)
summary(model)
anova(model)

# 5)
lm.beta(model)
```

### 02.

```{r}
data <- read.csv("./data/ch02/ex2-2.csv")
head(data)
model <- lm(Y ~ X1 + X2 + X3, data = data)

# 1)
summary(model)

# 2)
anova(model)

# 3)
newdata <- data.frame(X1 = 20, X2 = 27, X3 = 60)
predict(model, int = "p", newdata = newdata)
```

### 03.

```{r}
data <- read.csv("./data/ch02/chemical.csv")
head(data)

model <- lm(loss ~ speed + temp, data = data)
summary(model)
anova(model)

# 1)
confint(model)

# 2)
newdata <- data.frame(speed = 55, temp = 25)
predict(model, int = "c", newdata = newdata)

# 3-a)
plot(data$loss, model$resid)
# 3-b)
plot(data$speed, model$resid, pch = 19)
# 3-c)
plot(data$temp, model$resid, pch = 17)

# 4-a)
sum(model$resid)
# 4-b)
sum(model$fitted * model$resid)
# 4-c)
sum(data$speed * model$resid)
# 4-d)
sum(data$temp * model$resid)
```
