defmodule Emil.TestRepo.Migrations.Genesis do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:candle, primary_key: false) do
      add :id, :bigserial, null: false, primary_key: true
      add :open, :decimal, null: false
      add :high, :decimal, null: false
      add :low, :decimal, null: false
      add :close, :decimal, null: false
    end

    create table(:bot, primary_key: false) do
      add :id, :bigserial, null: false, primary_key: true
      add :name, :citext, null: false
    end
  end

  def down do
    drop table(:bot)

    drop table(:candle)
  end
end
