defmodule Emil.TestRepo.Migrations.MigrateResources1 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    execute("CREATE SCHEMA IF NOT EXISTS expression_test")

    create table(:token, primary_key: false, prefix: "expression_test") do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :expires_at, :utc_datetime, null: false
    end

    execute("CREATE SCHEMA IF NOT EXISTS aggregate_test")

    create table(:post, primary_key: false, prefix: "aggregate_test") do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
    end

    execute("CREATE SCHEMA IF NOT EXISTS aggregate_test")

    create table(:comment, primary_key: false, prefix: "aggregate_test") do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :content, :text, null: false

      add :post_id,
          references(:post,
            column: :id,
            name: "comment_post_id_fkey",
            type: :uuid,
            prefix: "aggregate_test"
          ),
          null: false
    end
  end

  def down do
    drop constraint(:comment, "comment_post_id_fkey", prefix: "aggregate_test")

    drop table(:comment, prefix: "aggregate_test")

    drop table(:post, prefix: "aggregate_test")

    drop table(:token, prefix: "expression_test")
  end
end
