defmodule Plato.Repo.Migrations.CreatePlatoResources do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:students, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :phone, :text
      add :grade, :bigint

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :campus_id, :uuid, null: false
    end

    create table(:problems, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :content, :text, null: false
      add :subject, :text, null: false
      add :difficulty, :text, null: false
      add :option_a, :text, null: false
      add :option_b, :text, null: false
      add :option_c, :text, null: false
      add :option_d, :text, null: false
      add :correct_answer, :text, null: false
      add :explanation, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :campus_id, :uuid, null: false
    end

    create table(:instructors, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :email, :text
      add :phone, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :campus_id, :uuid, null: false
    end

    create table(:campuses, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:students) do
      modify :campus_id,
             references(:campuses,
               column: :id,
               name: "students_campus_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:problems) do
      modify :campus_id,
             references(:campuses,
               column: :id,
               name: "problems_campus_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:instructors) do
      modify :campus_id,
             references(:campuses,
               column: :id,
               name: "instructors_campus_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:campuses) do
      add :name, :text, null: false
      add :address, :text
      add :phone, :text
      add :email, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end
  end

  def down do
    alter table(:campuses) do
      remove :updated_at
      remove :inserted_at
      remove :email
      remove :phone
      remove :address
      remove :name
    end

    drop constraint(:instructors, "instructors_campus_id_fkey")

    alter table(:instructors) do
      modify :campus_id, :uuid
    end

    drop constraint(:problems, "problems_campus_id_fkey")

    alter table(:problems) do
      modify :campus_id, :uuid
    end

    drop constraint(:students, "students_campus_id_fkey")

    alter table(:students) do
      modify :campus_id, :uuid
    end

    drop table(:campuses)

    drop table(:instructors)

    drop table(:problems)

    drop table(:students)
  end
end
